### ISSUE TITLE
Technical Spike: Using Java with OrientDB

### ISSUE THREAD

**Issue by swcurran** [bcgov/dcts#5]
Look at what is available for this setup.  Is this a recommended platform to build upon?

**Comment by GeorgeWalker** [comment]
Given that OrientDB is written in Java it also has the most support for Java clients.

It is available as a binary client, JDBC and also Spring.

Binary driver - http://orientdb.com/docs/last/Java-API.html
JDBC - http://orientdb.com/docs/last/JDBC-Home.html
Spring - https://github.com/orientechnologies/spring-data-orientdb

**Comment by GeorgeWalker** [comment]
Current progress - Data is now being imported and showing in OrientDB, using vertexes for the following objects:

Application
Module
Environment
Properties

Changes proposed:
Adjust the Environment such that there is only one Vertex for each Environment Type, so that you can easily query all items in Prod for example
Provide a mechanism to do the same for Property Keys
Review the UML diagram and update terminology on the graph
